### ISSUE TITLE
 Music does not play (ubuntu)

### ISSUE THREAD

**Issue by renat2985** [Atraci/Atraci#274]
Please help
~~~
./Atraci
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[4854:1230/205325:INFO:CONSOLE(1)] ""This module is meant to be used by cli. If you want to use ytdl programmatically, visit https://github.com/fent/node-ytdl-core"", source: /tmp/.org.chromium.Chromium.4uUMos/node_modules/ytdl/index.js (1)
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[4854:1230/205326:INFO:CONSOLE(1)] ""failed to fetch latvia.json"", source: file:///tmp/.org.chromium.Chromium.4uUMos/js/app.js (1)
[4854:1230/205332:INFO:CONSOLE(23)] ""VIDEOJS:" {"message":"Failed to set the 'currentTime' property on 'HTMLMediaElement': The element's readyState is HAVE_NOTHING.","name":"InvalidStateError","code":11,"stack":"Error: Failed to set the 'currentTime' property on 'HTMLMediaElement': The element's readyState is HAVE_NOTHING.\n    at Error (native)\n    at t.Kd (file:///tmp/.org.chromium.Chromium.4uUMos/js/vendor/video-js/video.js:105:92)\n    at V (file:///tmp/.org.chromium.Chromium.4uUMos/js/vendor/video-js/video.js:59:80)\n    at t.currentTime (file:///tmp/.org.chromium.Chromium.4uUMos/js/vendor/video-js/video.js:60:150)\n    at PlayTrack (file:///tmp/.org.chromium.Chromium.4uUMos/js/app.js:1:8526)\n    at HTMLDivElement.\u003Canonymous\u003E (file:///tmp/.org.chromium.Chromium.4uUMos/js/app.js:1:23765)\n    at HTMLDivElement.n.event.dispatch (file:///tmp/.org.chromium.Chromium.4uUMos/js/vendor/jquery-2.1.1.min.js:3:6404)\n    at HTMLDivElement.r.handle (file:///tmp/.org.chromium.Chromium.4uUMos/js/vendor/jquery-2.1.1.min.js:3:3179)"} "Video is not ready. (Video.js)"", source: file:///tmp/.org.chromium.Chromium.4uUMos/js/vendor/video-js/video.js (23)
[4854:1230/205332:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'entry' of undefined", source: file:///tmp/.org.chromium.Chromium.4uUMos/js/app.js (1)
[4854:1230/205333:INFO:CONSOLE(1)] ""failed to fetch latvia.json"", source: file:///tmp/.org.chromium.Chromium.4uUMos/js/app.js (1)

**Comment by fa7ad** [comment]
Atraci is discontinued sorry. :grin: 

you can check out another project by one of the contributors though [Kaku](http://kaku.rocks)

**Comment by reddit-is-fun** [comment]
@fa7ad Is this why the program crashes on Windows 10? I tried compatibility modes and running the program as administrator, no success.

**Comment by fa7ad** [comment]
probably, can't say for sure. 

personally i'm using kaku and sometimes mps-youtube. feel free to use anything else but atraci is not coming back afaik
